//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EveStats.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class APIConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal APIConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EveStats.Data.Resources.APIConstants", typeof(APIConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /latest/universe/structures/{0}.
        /// </summary>
        internal static string CitadelInfo {
            get {
                return ResourceManager.GetString("CitadelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://esi.evetech.net.
        /// </summary>
        internal static string ESIBase {
            get {
                return ResourceManager.GetString("ESIBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /latest/status/.
        /// </summary>
        internal static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://login.eveonline.com/oauth/.
        /// </summary>
        internal static string SSOBase {
            get {
                return ResourceManager.GetString("SSOBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to authorize/?response_type=code&amp;amp;redirect_uri={0}&amp;amp;client_id={3}&amp;amp;scope={2}&amp;amp;state={1}.
        /// </summary>
        internal static string SSOLogin {
            get {
                return ResourceManager.GetString("SSOLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:{0:D}/callback.
        /// </summary>
        internal static string SSORedirect {
            get {
                return ResourceManager.GetString("SSORedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /latest/universe/stations/{0}.
        /// </summary>
        internal static string StationInfo {
            get {
                return ResourceManager.GetString("StationInfo", resourceCulture);
            }
        }
    }
}
